[change] Updated CHANGES.rst
openwisp/django-swappable-models pull request #41
Opened 2021-11-11 11:30 UTC by codesankalp

2021-11-11 14:14 UTC, sheppard commented
Do we want to include a note that this is the first release under the new home?  I can come up with some verbiage if desired.

2021-11-12 15:16 UTC, nemesisdesign requested changes

2021-11-12 15:16 UTC, nemesisdesign commented on CHANGES.rst
> +- [deps] Dropped support for python<=3.6 and Django<2.2
this seems missing:
https://github.com/openwisp/django-swappable-models/commit/1ac54fc06e91d41acb0b4a52f877e711b4c6a6e4

2021-11-12 18:21 UTC, nemesisdesign approved these changes
:+1:

2021-11-12 18:59 UTC, nemesisdesign approved these changes

2021-11-12 19:00 UTC, merged